### ISSUE TITLE
Make workspaces code dynamic

### ISSUE THREAD

**Issue by janibashamd** [f5devcentral/f5xc-hybrid-security-architectures#59]
**Describe the bug**
Some of the current files in working code : https://github.com/janibashamd/f5-hybrid-security-architectures are seem to have static vars available like /arcadia/data.tf, /eks-cluster/data.tf, /nic/data.tf, /xc/data.tf etc

**To Reproduce**
1. Go to 'https://github.com/janibashamd/f5-hybrid-security-architectures '
2. Click on data.tf files in each section
3. Check values of each workspace

**Expected behavior**
Since these are user params, keeping static values won't work

**Screenshots**

**Comment by knowbase** [comment]
Fix validated and will be merged as part of release 2.3.1 on 25 May 2023.

**Comment by knowbase** [comment]
v2.3.1
