### ISSUE TITLE
Remove static values from user inputs

### ISSUE THREAD

**Issue by janibashamd** [f5devcentral/f5xc-hybrid-security-architectures#60]
**Is your feature request related to a problem? Please describe.**
Observed some of the env vars are considered as user inputs but after looking in the README observed they are static values. So why should they be considered as user input if they are same and non-changing values. For ex: VOLT_API_P12_FILE and NGINX_JWT

**Describe the solution you'd like**
If values are constants, they should be hard coded in the code

**Comment by knowbase** [comment]
Fix validated and will be merged as part of release 2.3.1 on 25 May 2023.

**Comment by knowbase** [comment]
v2.3.1
