### ISSUE TITLE
Hybrid Security Architectures Part 5 - NAP output "external_name" is not getting populated in Terraform Cloud outputs

### ISSUE THREAD

**Issue by ishikaray16** [f5devcentral/f5xc-hybrid-security-architectures#87]
**Describe the bug**
While testing [https://community.f5.com/kb/technicalarticles/f5-hybrid-security-architectures-part-5---f5-xc-big-ip-apm-cis-and-nginx-ingress/320168]
NGINX App Protect output "external_name" is not getting populated in Terraform Cloud outputs. Resulting in the below error in the run.

`│ Error: Error in function call
│ 
│   on ingress.tf line 9, in resource "kubernetes_ingress_v1" "***-ingress":
│    9:       host = try(data.tfe_outputs.nap[0].values.external_name, data.tfe_outputs.nic[0].values.external_name)
│     ├────────────────
│     │ while calling try(expressions...)
│ 
│ Call to function "try" failed: no expression succeeded:
│ - Unsupported attribute (at ingress.tf:9,48-62)
│   This object does not have an attribute named "external_name".
│ - Unsupported attribute (at ingress.tf:9,94-108)
│   This object does not have an attribute named "external_name".
│ 
│ At least one expression must produce a successful result.`

**To Reproduce**
1. Configure github and Terraform cloud with variables and tokens mentioned in the article
2. Create/navigate to branch deploy-xcbn-cis, and configure infra/terraform.tfvars accordingly 
3. Push the changes to trigger the run
4. Infra, EKS, BIGIP base, BIGIP CIS, NAP were successful 
5. One of the outputs created from NAP run is not accessible to ARCADIA runs

**Expected behavior**
Output "external_name" should have been populated in terraform cloud and logs under NAP. 

**Screenshots**
<img width="1556" alt="Screenshot 2024-10-17 at 11 28 45 AM" src="https://github.com/user-attachments/assets/ddf7920b-36f2-4f43-a302-0eff9f5e1640">
<img width="1598" alt="Screenshot 2024-10-17 at 11 29 21 AM" src="https://github.com/user-attachments/assets/d28912c4-d744-43f3-949d-5a8b7daafa73">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome
 - Version 130.0.6723.59

**Smartphone (please complete the following information): NA**

**Additional context**
Also, instead of creating new nginx-service the run is only refreshing the already existing resource even though no resource is available in the region.
<img width="1683" alt="Screenshot 2024-10-17 at 9 20 08 PM" src="https://github.com/user-attachments/assets/b2ee22a1-1b3a-4f3d-9bf6-eeb20a9d759e">

**Comment by janibashamd** [comment]
Able to debug with others and found issue is because of changes in bigip CIS related CRD's. @ishikaray16 will commit the new changes in coming days after testing them.

**Comment by ishikaray16** [comment]
The resolution is covered under the PR https://github.com/f5devcentral/f5-hybrid-security-architectures/pull/89 (merged). So, closing this.
